"""empty message

Revision ID: 2b56e5ff23a7
Revises: 23ab2a71ac6c
Create Date: 2018-10-18 14:53:01.305419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b56e5ff23a7'
down_revision = '23ab2a71ac6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imagesrc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imagesrc')
    # ### end Alembic commands ###
